parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: functionAppName
  default: ''
- name: resourceGroupName
  default: ''
- name: storageAccountName
  default: ''
- name: region
  default: ''
- name: packageName
  default: ''
- name: cosmosDbName
  default: ''  

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'vs2017-win2016'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'CosmosDB - Deploy'
              inputs:
                azureResourceManagerConnection: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/cosmos-db.json'
                overrideParameters: '-accountName ${{ parameters.cosmosDbName }} -databaseName "MeasurementDB"'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - powershell: |
                $outputs = ConvertFrom-Json $($env:ResourceGroupDeploymentOutputs)
   
                foreach ($output in $outputs.PSObject.Properties) {
                    Write-Host "##vso[task.setvariable variable=RGDO_$($output.Name)]$($output.Value.value)"
                }
   
              displayName: 'CosmosDB - Capture Outputs'

            - task: AzureResourceGroupDeployment@3
              displayName: '3. Create Function Infrastructure'
              inputs:
                azureResourceManagerConnection: ${{ parameters.azureSubscription }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.region }}
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName ${{ parameters.functionAppName }} -storageAccountName ${{ parameters.storageAccountName }}'
                deploymentOutputs: ResourceGroupDeploymentOutputs
 
            - task: AzureFunctionApp@1
              displayName: '4. Azure functions app deploy'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: functionApp
                appName: ${{ parameters.functionAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.packageName }}'
                AppSettings: '-CosmosDBConnection $(RGDO_cosmosConnectionString)'