trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-function-cosmos-db - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'Demo Account'
  region: 'East US'
  packageName: 'Demo.Function.API.zip'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'API-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'rutzsco-function-api-cosmos-db-ci'
    resourceGroupName: 'rutzsco-function-api-cosmos-db-ci'
    storageAccountName: 'azfuncapicdb1ci'
    region: ${{ variables.region }}
    packageName: ${{ variables.packageName }}
    cosmosDbName: 'rutzsco-demo-cosmos-db-ci'
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'QA'
    environment: 'API-QA'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'demo-function-api-qa'
    resourceGroupName: 'demo-function-api-qa'
    storageAccountName: 'azfuncapicdb1qa'
    region: ${{ variables.region }}
    packageName: ${{ variables.packageName }}
    cosmosDbName: 'rutzsco-demo-cosmos-db-qa'