trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'demo-az-function-api-cosmos-db - BUILD'
  
variables:
  vmImageName: 'ubuntu-latest'
  azureSubscription: 'Demo Account'
  region: 'East US'
  resourceGroupName: 'rutzsco-function-api-cosmos-db'
  functionAppName: 'rutzsco-function-api-cosmos-db' 
  functionAppStorageAccountName: 'azfuncapicdb1' 
stages:
 - stage: CI
   displayName: CI stage 
  
   jobs:
   - deployment: Deploy
     displayName: Deploy
     environment: 'CI'
     pool:
        vmImage: $(vmImageName)   
      
     strategy:
        runOnce:
          deploy:
  
            steps:
                       
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'CosmosDB - Deploy'
              inputs:
                azureResourceManagerConnection: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/cosmos-db.json'
                overrideParameters: '-accountName "rutzsco-demo-cosmos-db" -databaseName "MeasurementDB"'
                deploymentOutputs: ResourceGroupDeploymentOutputs

            - powershell: |
                $outputs = ConvertFrom-Json $($env:ResourceGroupDeploymentOutputs)
   
                foreach ($output in $outputs.PSObject.Properties) {
                    Write-Host "##vso[task.setvariable variable=RGDO_$($output.Name)]$($output.Value.value)"
                }
   
              displayName: 'CosmosDB - Capture Outputs'

            - task: AzureResourceGroupDeployment@3
              displayName: '3. Create Function Infrastructure'
              inputs:
                azureResourceManagerConnection: '$(azureSubscription)'
                resourceGroupName: '$(resourceGroupName)'
                location: '$(region)'
                csmFile: '$(Pipeline.Workspace)/build/Infrastructure/function-app-consumption.json'
                overrideParameters: '-appName $(functionAppName) -storageAccountName $(functionAppStorageAccountName)'
                deploymentOutputs: ResourceGroupDeploymentOutputs
 
            - task: AzureFunctionApp@1
              displayName: '4. Azure functions app deploy'
              inputs:
                azureSubscription: '$(azureSubscription)'
                appType: functionApp
                appName: $(functionAppName)
                package: '$(Pipeline.Workspace)/build/App/Demo.Function.Api.zip'
                AppSettings: '-CosmosDBConnection $(RGDO_cosmosConnectionString)'